/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData football_ball_variant = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medical_result = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar__1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tournament = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supermarket_gift = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData olive_branches_award_symbol = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy__1_ = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home__1_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
